<h3>    What is Numpy </h3>

NumPy, short for Numerical Python, is one of the most important foundational pack‐
ages for numerical computing in Python. Most computational packages providing
scientific functionality use NumPy’s array objects as the lingua franca for data
exchange.

<h4> What numpy provides: </h4>

<ul>
    <li> ndarray, an efficient multidimensional array providing fast array-oriented arith‐
metic operations and flexible broadcasting capabilities. </li>
    <li> Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops. </li>
    <li> Linear algebra, random number generation </li>
    <li> A C API for connecting NumPy with libraries written in C, C++ </li>
</ul>

<h4> Why using It instead of python's list </h4>

<ul>
    <li> Provide matrix and vector operations </li>
    <li> It's written in C optimized code. Much more faster and memory efficient.(up to hundreds time faster and ten's time more memory efficient</li>
    <li>provides an easy-to-use C API, it is straightforward to pass data to
external libraries written in a low-level language and also for external libraries to
        return data to Python as NumPy arrays.</li>
</ul>

<h3> Deference between numpy array and python's list </h3><br><br><br>
<img src="https://raw.githubusercontent.com/h8hawk/Datacamp-Scientific-Python/master/files/array_vs_list.png"/>

<h3> What provides in this courese? </h3>

<ul>
    <li> Fast vectorized array operations for data munging and cleaning, subsetting and
        filtering, transformation, and any other kinds of computations </li>
    <li> Common array algorithms like sorting, unique, and set operations </li>
    <li> Efficient descriptive statistics and aggregating/summarizing data </li>
    <li> Data alignment and relational data manipulations for merging and joining
        together heterogeneous datasets </li>
    <li> Expressing conditional logic as array expressions instead of loops with if-elif-
        else branches </li>
    <li> Group-wise data manipulations (aggregation, transformation, function applica‐
        tion)</li>
</ul>


<h4> How numpy works </h4>

<ul>
    <li> NumPy internally stores data in a contiguous block of memory, independent of
other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead.
        NumPy arrays also use much less memory than built-in Python sequences. </li>
    <li> NumPy operations perform complex computations on entire arrays without the
    need for Python for loops. </li>
    
</ul>


<h4> The NumPy ndarray: A Multidimensional Array Object </h4>

<p> One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements. </p>




<h4> First look at numpy array: </h4>

Importing numpy module and prefixing it by <b>np</b>:

In [2]:
import numpy as np

Generate Some random data.  
<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState">How numpy generate random numbers? </a>

In [3]:
data = np.random.randn(2,3)

In [4]:
data

array([[ 1.46400028, -0.43855219,  2.00429042],
       [-0.31404764, -0.14072682, -0.99101898]])

<p> Mathematical operation with <b>data</b> </p>

In [5]:
data * 10

array([[14.64000275, -4.38552193, 20.04290424],
       [-3.14047641, -1.40726824, -9.91018984]])

<p> all of the elements of <b>data</b> have been multiplied by 10. </p>

<h3> Some properties of numpy array's (ndarray) </h3>
<ul>
    <li> An ndarray is a generic multidimensional container for homogeneous data : all
        of the elements must be the same type. </li>
    <li> Every array has a <b>shape</b> : a tuple indicating the
        size of each dimension </li>
    <li> Every array has a <b>dtype</b> : an object describing the data type of the array </li>
</ul>

For 'data':

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

<h3> Creating ndarray's </h3>
<ul>
    <li> Easies way: using <b>array</b> function </li>
</ul>

First make python list:

In [8]:
data1 = [4, 5.3, 8, 9, 12]

In [9]:
arr1 = np.array(data1)

In [10]:
print(arr1)

[ 4.   5.3  8.   9.  12. ]


Nested sequence :

In [11]:
nested_seq = [[1, 2, 3], [4, 5, 6]]

In [12]:
nested_arr = np.array(nested_seq)

In [13]:
print(nested_arr)

[[1 2 3]
 [4 5 6]]


In [14]:
nested_arr.ndim

2

In [15]:
nested_arr.shape

(2, 3)

In [16]:
nested_arr.dtype

dtype('int64')

<h3> Some properties of numpy array's (ndarray) </h3>
<ul>
    <li> Unless explicitly specified, <b>np.array</b> tries to infer a good data
        type for the array that it creates. The data type is stored <b>dtype</b> </li>
</ul>
</br>

<h4> There are a number of other functions for creating new
arrays: </h4>
<ul>
    <li> <b>zeros</b> : create arrays of 0s </li>
    <li> <b>ones</b> : create arrays of 1s </li>
    <li> <b>empty</b> : creates an array without initializing its values to any particular value.</li>
    <li> <b>arange</b> : Like the built-in <b>range</b> but returns an ndarray instead of a list</li>
    <li> <b> ones_like </b> : produces a ones array of the same shape and dtype </li>
    <li> <b> zeros_like </b> : Like <b>ones_like</b> but for zeros </li>
    <li> <b> full </b> : Produce an array of the given shape and dtype with all values set to the indicated “fill value”</li>
    <li> <b> eye</b>, <b>identity </b> : Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere) 
</ul>

In [17]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty((4,6))

array([[1.23962019e-316, 7.58445798e-302, 2.01160983e-309,
        9.77801185e+199, 2.44046782e-152, 1.27587196e-152],
       [1.13224202e+277, 1.33360307e+241, 1.87160029e-311,
        1.70182262e-123, 1.00678753e-312, 6.52094399e-308],
       [3.32653140e-111, 3.33481217e+079, 6.88488166e-313,
        4.85213860e-308, 2.27610565e-159, 2.64171898e-313],
       [1.27631071e-303, 5.12965257e+064, 5.58599989e+093,
        9.08367206e+223, 1.13224202e+277, 1.43485896e+161]])

<p> <b>empty</b>, unlike <b>zeros</b>, does not set the array values to zero, and may therefore be marginally faster. <br><b>empty</b> has nothing to do with creating an array that is "empty" in the sense of having no elements. It just means the array doesn't have its values initialized (i.e., they are unpredictable and depend on whatever happens to be in the memory allocated for the array).</p>

In [20]:
np.full((3,4), 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [21]:
np.ones_like(nested_arr)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,10,.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

<h4>Data Types for ndarrays:</h4>
<ul>
<li> The data type or dtype is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular
type of data. </li>
</ul>

In [24]:
arr1 = np.array([1, 2, 3, 4], dtype=np.float32)

In [25]:
arr1

array([1., 2., 3., 4.], dtype=float32)

In [26]:
arr2 = np.array([1.2, 3, -0.3], dtype=np.int32)

In [27]:
arr2

array([1, 3, 0], dtype=int32)

<h6> Casting floating-pint to intger: the decimal part will be truncated: </h6>

<h3> Numpy data types </h3>
<ul>
    <li> <b> int8, uint8 </b> : Signed and unsigned 8-bit (1 byte) integer types </li>
    <li> <b> int16, uint16 </b> : Signed and unsigned 16-bit integer types </li>
    <li> <b> int32, uint32 </b> : Signed and unsigned 32-bit integer types </li>
    <li> <b> int64, uint64 </b> : Signed and unsigned 64-bit integer types </li>
    <li> <b> float16 </b> : Half-precision floating point </li>
    <li> <b> float32 </b> : Standard single-precision floating point; compatible with C float </li>
    <li> <b> float64 </b> : Standard double-precision floating point; compatible with C double and
    Python float object </li>
    <li> <b> float128 </b> : Extended-precision floating point </li>
    <li> <b> complex64, complex128 </b> : Complex numbers represented by two 32, 64, or 128 floats, respectively </li>
    <li> <b> bool </b> : Boolean type storing True and False values </li>
    <li> <b> object </b> : Python object type; a value can be any Python object </li>
    <li> <b> string_ </b> : Fixed-length ASCII string type (1 byte per character); for example, to create a
    string dtype with length 10, use 'S10' </li>
    <li> <b> unicode_ </b> : Fixed-length Unicode type (number of bytes platform specific); same
specification semantics as string_ (e.g., 'U10' ) </li>
</ul><br><br>
<h5> Convert array's dtype : <b>astype</b> method </h5>



In [28]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [29]:
float_arr = arr.astype(np.float32)

In [30]:
float_arr.dtype

dtype('float32')

<h6> Casting floating-pint to intger: the decimal part will be truncated: </h6>

In [31]:
string_arr = np.array(['ab', '1' , 'fj'], dtype=np.string_)

In [32]:
string_arr.dtype

dtype('S2')

In [33]:
string_arr.astype(np.int64)

ValueError: invalid literal for int() with base 10: 'ab'

<h3> Arithmetic with NumPy Arrays </h3>
<ul>
<li>Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this vectorization. Any arithmetic
operations between equal-size arrays applies the operation element-wise: </li>
</ul>

In [34]:
arr = np.array([[1, 2 , 3], [4, 5, 6]], dtype=np.float64)

In [35]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [36]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

<p>Arithmetic operations with scalars propagate the scalar argument to each element in
the array:</p>

In [37]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [38]:
arr ** 5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

<p>Comparisons between arrays of the same size yield boolean arrays:</p>

In [39]:
arr2 = np.array([[0, 5, 1], 
                 [6, 5 , 10]], dtype=np.float64)

In [40]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [41]:
arr2 == arr

array([[False, False, False],
       [False,  True, False]])

<h4>Important term : broadcasting </h4>

<ul>
    <li> Operations between differently sized arrays is called <b>broadcasting</b> </li>
    <li> Broadcasting is the process of making arrays with different shapes have compatible shapes for arithmetic operations. </li>
</ul>

<p> Here we say that the scalar value 4 has been broadcast to all of the other elements in
the multiplication operation. : </p>

In [42]:
arr * 4

array([[ 4.,  8., 12.],
       [16., 20., 24.]])

In [43]:
arr + 4

array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

<h3> Indexing and Slicing</h3>
<ul>
    <li> <b>arr[start:stop:step]</b> for 1d arrays </li>
    <li> <b>arr[start:stop:step, start:stop:step, ....]</b> for more than  1d arrays </li> 
<ul>

In [44]:
arr = np.arange(20)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
arr[4]

4

In [47]:
arr[4:7]

array([4, 5, 6])

In [48]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[2:10:2]

array([2, 4, 6, 8])

<p><b>Tip: </b> In numpy arrays and python's list [a:b] slicing from N index means [a,b) in math. or [a, b-1]

In [50]:
arr[3:5] = 256
# arr.__setitem__(slice(3,5), 256)

In [51]:
arr

array([  0,   1,   2, 256, 256,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

<h4>Advanced Tip :</h4>
<ul>
    <li> <b>arr[start:stop:step]</b> means: <b>arr[slice(start, stop, step)]</b> </li>
    <li> <b> arr[index] </b> means: <b>arr.__getitem__(index)</b>
    <li> <b>arr[index] = value </b> means: <b>arr.__setitem__(index, value)</b> </li>
</ul>
<p> numpy use above facilities to enhance user experience </p><br>

In [52]:
arr_slice = arr[1:4]

In [53]:
arr_slice

array([  1,   2, 256])

In [54]:
arr_slice[0]=9999

In [55]:
arr

array([   0, 9999,    2,  256,  256,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

<p> change values in arr_slice , the mutations are reflected in the original array arr </p><br>

<h4> Slicing in higher dimension arrays: </h4><br>

In [56]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2d[1]

array([4, 5, 6])

In [59]:
arr2d[2][0]

7

In [60]:
arr2d[2, 1]

8

<h4>Indexing elements in a NumPy array</h4><br>
<img src="https://raw.githubusercontent.com/h8hawk/Datacamp-Scientific-Python/master/files/numpy_2darray.jpg"/>

In [61]:
arr2d[:2, 1:] # Rows: start until 2  , columns: 1 until end

array([[2, 3],
       [5, 6]])

In [62]:
arr2d[:2, 2] 

array([3, 6])

In [63]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [64]:
arr2d[:, 1]

array([2, 5, 8])

<h4> Boolean Indexing </h4>
<p> This boolean array can be passed when indexing the array. </p><br>

In [65]:
data = np.random.randn(4, 4)

In [66]:
boolean_index = (data < -.5) | (data > .5)

In [67]:
boolean_index

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [False,  True,  True,  True]])

In [68]:
data[boolean_index]

array([-0.81190105,  0.64287157, -0.81643838,  0.83030652,  1.24279776,
        2.78548325,  1.82132827,  0.93615469,  1.44382825, -0.76769643,
        0.87566673])

<h4> Fancy Indexing :</h4><br>

In [69]:
arr = np.random.randn(8, 4)

In [70]:
arr

array([[ 0.71095284, -0.21156428, -1.02465039,  1.06395832],
       [ 1.24830765, -0.52586605,  1.19669432,  0.59715744],
       [-1.60072449, -1.87457114,  1.86685975, -1.11385137],
       [-0.41914867, -0.30478736,  1.14078682,  0.61781727],
       [ 0.53591623, -0.22937595, -0.05659173,  0.18207533],
       [-0.76107827,  0.90820175, -0.40861742,  0.40199009],
       [ 2.09230733, -0.31575278, -0.3389437 , -0.1356881 ],
       [-0.82547347, -2.22851079,  1.87552509,  1.39262296]])

In [71]:
arr[[4, 3, 0, 6]]

array([[ 0.53591623, -0.22937595, -0.05659173,  0.18207533],
       [-0.41914867, -0.30478736,  1.14078682,  0.61781727],
       [ 0.71095284, -0.21156428, -1.02465039,  1.06395832],
       [ 2.09230733, -0.31575278, -0.3389437 , -0.1356881 ]])

In [72]:
arr[[1, 6], [3, 1]]

array([ 0.59715744, -0.31575278])

<h3> Reshaping and Transposing Arrays and Swapping Axes </h3><br>

In [74]:
arr = np.arange(15)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
arr.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.reshape((4,8))

ValueError: cannot reshape array of size 15 into shape (4,8)

In [82]:
arr = arr.reshape((5,3))

In [83]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [84]:
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

<h4> Universal Functions: Fast Element-Wise Array Functions </h4>
<ul>
    <li>A universal function, or <b>ufunc</b>, is a function that performs element-wise operations
        on data in ndarrays.</li>
</ul><br>

In [103]:
arr = np.arange(10)

In [104]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [107]:
np.max(arr)

9

In [108]:
np.min(arr)

0

In [110]:
np.mean(arr)

4.5

In [111]:
np.absolute(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<p> These are referred to as unary ufuncs. Others, such as add or maximum , take two arrays
(thus, binary ufuncs) and return a single array as the result: </p>

In [112]:
x = np.random.randn(6)

In [113]:
y = np.random.randn(6)

In [114]:
x, y

(array([-0.44458166, -0.29257846, -0.61201424,  0.27316785, -0.2963726 ,
        -0.19993381]),
 array([-0.54979466,  0.36048926, -0.2193441 , -1.50527013, -1.0900603 ,
         0.85222855]))

In [115]:
np.maximum(x, y)

array([-0.44458166,  0.36048926, -0.2193441 ,  0.27316785, -0.2963726 ,
        0.85222855])

<h4> Unary ufuncs:  </h4>
<ul>
    <li><b>abs, fabs</b> : Compute the absolute value element-wise for integer, floating-point, or complex values</li>
    <li><b>sqrt</b> : Compute the square root of each element (equivalent to arr ** 0.5 )</li>
    <li><b>square</b> : Compute the square of each element (equivalent to arr ** 2 )</li>
    <li><b>exp</b> : Compute the exponent e x of each element</li>
        <li><b>log, log10, log2, log1p</b> : Natural logarithm (base e), log base 10, log base 2, and log(1 + x),  respectively</li>
    <li><b>sign</b> : Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)</li>
    <li><b>ceil</b> : Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that
number) </li>
    <li><b>floor</b> : Compute the floor of each element (i.e., the largest integer less than or equal to each element) </li>
    <li><b>rint</b> : Round elements to the nearest integer, preserving the dtype </li>
    <li><b>modf</b> : Return fractional and integral parts of array as a separate array</li>
    <li><b>isnan</b> : Return boolean array indicating whether each value is NaN (Not a Number) </li>
    <li><b>isfinite, isinf </b> : Return boolean array indicating whether each element is finite (non- inf , non- NaN ) or infinite,
respectively </li>
    <li><b>cos, cosh, sin, sinh, tan, tanh</b> : Regular and hyperbolic trigonometric functions</li>
    <li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</b> : Inverse trigonometric functions </li>
    <li><b>logical_not</b> : Compute truth value of not x element-wise (equivalent to ~arr ). </li>
</ul>

    

<h3> Binary universal functions: </h3>
<ul>
    <li><b>add</b> : Add corresponding elements in arrays</li>
    <li><b>subtract</b> : Subtract elements in second array from first array</li>
    <li><b>multiply</b> : Multiply array elements</li>
    <li><b>divide, floor_divide</b> : Divide or floor divide (truncating the remainder)</li>
    <li><b>power</b> : Raise elements in first array to powers indicated in second array</li>
    <li><b>maximum, fmax</b> : Element-wise maximum; fmax ignores NaN</li>
    <li><b>minimum, fmin</b> : Element-wise minimum; fmin ignores NaN</li>
    <li><b>mod</b> : Element-wise modulus (remainder of division)</li>
    <li><b>copysign</b> : Copy sign of values in second argument to values in first argument</li>
    <li><b>greater, greater_equal, less, less_equal, equal, not_equal</b> : Perform element-wise comparison, yielding boolean array (equivalent to infix
operators >, >=, <, <=, ==, !=)</li>
    <li><b>logical_and, logical_or, logical_xor</b> : Compute element-wise truth value of logical operation (equivalent to infix operators
& |, ^ )</li>

</ul>